### ISSUE TITLE
documentation reference ClusterConfig object which does not exists

### ISSUE THREAD

**Issue by josephnatale** [aterleto/jedis#8]
Maybe just a bit of doc that needs updating but the [usage doc](https://github.com/aterleto/jedis/blob/cross-cluster-failover/docs/failover.md#basic-usage) is referencing an object called ClusterConfig which is used to define specific Redis clusters, after adding the Jedis dependency this object is unable to be resolved.  However, the MultiClusterJedisClientConfig.ClusterJedisClientConfig object looks to be what the API needs, maybe just a bit of documentation updating needed here?

**Comment by aterleto** [comment]
Hi Joe, you may have caught us right in between a couple commits between the docs and code as we prepped to merge with main. It should all be consistent by now. Please use the latest and let us know if you still get that problem.

**Comment by josephnatale** [comment]
[this branch](https://github.com/aterleto/jedis/blob/cross-cluster-failover/docs/failover.md) still references the 'ClusterConfig' object.  Sounds like you have it on your rador, I'll close this.
